steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/stats-nerd/iks-ui-demo']

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g sonarqube-scanner

  - name: 'gcr.io/cloud-builders/sonar-scanner'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner


  # Build the Docker image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-docker.pkg.dev/storied-surface-415206/iksuidocker/iksuiimage:v3', '.']
   
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-docker.pkg.dev/storied-surface-415206/iksuidocker/iksuiimage:v3']
 
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'iksuiservice'
      - '--image'
      - 'asia-docker.pkg.dev/storied-surface-415206/iksuidocker/iksuiimage:v3'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west2'
      - '--port=80'
      - '--allow-unauthenticated'